### PR TITLE
Updating to use compiler as plugin

### PR DESCRIPTION
**Pull request by shughes-uk**
## Changes
- Use NPM versions of Pipewrench/Events
- npm-watch instead of custom watcher
- github actions
- Compiler plugin instead of opinionated compile.js
## Removed
- Header/Footer inclusion stuff, return at a later date in the compiler plugin
- .d.ts export (return asap)

### CODE REVIEW

**Comment by shughes-uk** [comment]
@JabDoesThings ready for review!

**Comment by JabDoesThings** [comment]
Isn't npm's watcher poorly supportive for other operating systems? I initially did what I did using my solution to avoid this issue.

**Comment by shughes-uk** [comment]
> Isn't npm's watcher poorly supportive for other operating systems? I initially did what I did using my solution to avoid this issue.

Apparently fine on macos/windows and maybe not quite as fast on linux? Not sure that means it's worth implementing something totally custom

**Comment by JabDoesThings** [comment]
> 

If you feel that the custom watcher is not proper, we can try this approach. If we run into issues, this can be reversed or improved on.

**Review by JabDoesThings — APPROVED** [review]
Reimplementing exported definitions will be the next immediate task for this project.

**Pull request merged**
